# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - ur_shoulder_pan_joint
    - ur_shoulder_lift_joint
    - ur_elbow_joint
    - ur_wrist_1_joint
    - ur_wrist_2_joint
    - ur_wrist_3_joint
    - bl_caster_rotation_joint
    - bl_caster_wheel_joint
    - br_caster_rotation_joint
    - br_caster_wheel_joint
    - fl_caster_rotation_joint
    - fl_caster_wheel_joint
    - fr_caster_rotation_joint
    - fr_caster_wheel_joint
    - left_wheel_joint
    - right_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS

controller_list:
- name: "scaled_pos_joint_traj_controller"
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - ur_shoulder_pan_joint
    - ur_shoulder_lift_joint
    - ur_elbow_joint
    - ur_wrist_1_joint
    - ur_wrist_2_joint
    - ur_wrist_3_joint